import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    // Bundled one-off entrypoints generated by build:scripts (not source).
    "dist/**",
    "next-env.d.ts",
    // Local design-handoff bundle (reference only, not part of the app).
    "claude-design/**",
  ]),
]);

export default eslintConfig;
